# Generated by Django 2.1.5 on 2019-01-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_web_app', '0002_auto_20190113_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
